export default defineAppConfig({
  items: {
    food: {
      name: 'Comida para patos',
      description: 'Alimenta a los patos',
      img: 'item_food.png',
      costBase: 4n,
      rateGrowth: 1.07,
      time: 0.6,
      revenueBase: 1n,
    },
    lily: {
      name: 'Nenúfares',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_lily.png',
      costBase: 60n,
      rateGrowth: 1.15,
      time: 3,
      revenueBase: 60n,
    },
    divingKit: {
      name: 'Equipo de buceo',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_diving_kit.png',
      costBase: 720n,
      rateGrowth: 1.14,
      time: 6,
      revenueBase: 540n,
    },
    lotus: {
      name: 'Flor de loto',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_lotus.png',
      costBase: 8_640n,
      rateGrowth: 1.13,
      time: 12,
      revenueBase: 4_320n,
    },
    frog: {
      name: 'Rana',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_frog.png',
      costBase: 103_680n,
      rateGrowth: 1.12,
      time: 24,
      revenueBase: 51_840n,
    },
    koi: {
      name: 'Peces koi',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_koi.png',
      costBase: 1_244_160n,
      rateGrowth: 1.11,
      time: 96,
      revenueBase: 622_080n,
    },
    fountain: {
      name: 'Fuente para patos',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_fountain.png',
      costBase: 14_929_920n,
      rateGrowth: 1.10,
      time: 384,
      revenueBase: 7_464_960n,
    },
    lantern: {
      name: 'Farolillo',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_lantern.png',
      costBase: 179_159_040n,
      rateGrowth: 1.09,
      time: 1_536,
      revenueBase: 89_579_520n,
    },
    thermalBath: {
      name: 'Baño termal',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_thermal_bath.png',
      costBase: 2_149_908_480n,
      rateGrowth: 1.08,
      time: 6_144,
      revenueBase: 1_074_954_240n,
    },
    house: {
      name: 'Casa para patos',
      description: 'Aumenta la felicidad de los patos',
      img: 'item_house.png',
      costBase: 25_798_901760n,
      rateGrowth: 1.07,
      time: 36_864,
      revenueBase: 29_668_737_024n,
    },
  },
  managers: {
    food: {
      name: 'Manager de comida',
      description: 'Encargado de alimentar automáticamente',
      img: 'manager_food.png',
      cost: 1_000n,
    },
    lily: {
      name: 'Manager de nenúfares',
      description: 'Encargado de cuidar los nenúfares',
      img: 'manager_lily.png',
      cost: 15_000n,
    },
    divingKit: {
      name: 'Manager de equipo de buceo',
      description: 'Encargado repartir equipos de buceo a los patos',
      img: 'manager_diving_kit.png',
      cost: 100_000n,
    },
    lotus: {
      name: 'Manager de flores de loto',
      description: 'Encargado de cuidar las flores de loto',
      img: 'manager_lotus.png',
      cost: 500_000n,
    },
    frog: {
      name: 'Manager de ranas',
      description: 'Encargado de cuidar las ranas',
      img: 'manager_frog.png',
      cost: 1_200_000n,
    },
    koi: {
      name: 'Manager de peces koi',
      description: 'Encargado de cuidar los peces koi',
      img: 'manager_koi.png',
      cost: 10_000_000n,
    },
    fountain: {
      name: 'Manager de fuentes para patos',
      description: 'Encargado de cuidar las fuentes para patos',
      img: 'manager_fountain.png',
      cost: 111_111_111n,
    },
    lantern: {
      name: 'Manager de farolillos',
      description: 'Encargado de instalar farolillos en el estanque',
      img: 'manager_lantern.png',
      cost: 555_555_555n,
    },
    thermalBath: {
      name: 'Manager de baños termales',
      description: 'Encargado de cuidar los baños termales',
      img: 'manager_thermal_bath.png',
      cost: 1_0000_000_000n,
    },
    house: {
      name: 'Manager de casas para patos',
      description: 'Encargado de cuidar las casas para patos',
      img: 'manager_house.png',
      cost: 100_000_000_000n,
    },
  },
  upgrades: [
    {
      item: 'food',
      name: 'Comida de calidad',
      description: 'Aumenta la eficiencia de la comida de los patos x3',
      cost: 250_000n,
      effect: 3,
    },
    {
      item: 'lily',
      name: 'Nenúfares ergonómicos',
      description: 'Aumenta la eficiencia de los nenúfares x3',
      cost: 500_000n,
      effect: 3,
    },
    {
      item: 'divingKit',
      name: 'Equipo de buceo de calidad',
      description: 'Aumenta la eficiencia del equipo de buceo x3',
      cost: 1_000_000n,
      effect: 3,
    },
    {
      item: 'lotus',
      name: 'Flores de loto despampanantes',
      description: 'Aumenta la eficiencia de las flores de loto x3',
      cost: 5_000_000n,
      effect: 3,
    },
    {
      item: 'frog',
      name: 'Ranas de la suerte',
      description: 'Aumenta la eficiencia de las ranas x3',
      cost: 10_000_000n,
      effect: 3,
    },
    {
      item: 'koi',
      name: 'Peces koi gigantes',
      description: 'Aumenta la eficiencia de los peces koi x3',
      cost: 25_000_000n,
      effect: 3,
    },
    {
      item: 'fountain',
      name: 'Fuentes para patos de 50L',
      description: 'Aumenta la eficiencia de las fuentes para patos x3',
      cost: 500_000_000n,
      effect: 3,
    },
    {
      item: 'lantern',
      name: 'Farolillos de lujo',
      description: 'Aumenta la eficiencia de los farolillos x3',
      cost: 10_000_000_000n,
      effect: 3,
    },
    {
      item: 'thermalBath',
      name: 'Baños termales calentitos',
      description: 'Aumenta la eficiencia de los baños termales x3',
      cost: 50_000_000_000n,
      effect: 3,
    },
    {
      item: 'house',
      name: 'Mansiones para patos',
      description: 'Aumenta la eficiencia de las casas para patos x3',
      cost: 250_000_000_000n,
      effect: 3,
    },
    {
      item: 'ALL',
      name: 'Estanque renovado',
      description: 'Aumenta la eficiencia de todos los objetos x3',
      cost: 1_000_000_000_000n,
      effect: 3,
    },
  ],
  achievements: {
    currency: {
      hundred: {
        name: '100 monedas',
        description: 'Conseguido por conseguir 100 monedas',
      },
    },
    item: {
      food25: {
        name: '',
        description: 'Obtenido por llegar al nivel 25 de comida para patos',
      },
    },
    easteregg: {
      konami: {
        name: 'El KonamiPato',
        description: 'Conseguido por introducir el código Konami',
      },
    },
    rare: {
      top1: {
        name: 'Top #1 Mundial!',
        description: 'Conseguido por ser el top #1 mundial',
      },
      allAchievements: {
        name: 'Todos los logros!',
        description: 'Conseguido por conseguir todos los logros',
      },
      kuroJam: {
        name: 'KuroJam',
        description: 'Conseguido por jugar durante la KuroJam',
      },
    },
  },
  skins: {
    default: {
      name: 'Pato',
      description: 'Pato tonto',
      img: 'skin_default.png',
    },
  },
})
