export default defineAppConfig({
  items: {
    food: {
      name: 'Panecillos',
      description: '¡Comidita pa-tol mundo!',
      img: 'item_food.png',
      costBase: 4,
      rateGrowth: 1.07,
      time: 600,
      revenueBase: 1,
    },
    lily: {
      name: 'Nenúfar',
      description: 'Barcos en el estanque.',
      img: 'item_lily.png',
      costBase: 60,
      rateGrowth: 1.15,
      time: 3_000,
      revenueBase: 60,
    },
    divingKit: {
      name: 'Equipo de buceo',
      description: 'Patos subacuáticos.',
      img: 'item_diving_kit.png',
      costBase: 720,
      rateGrowth: 1.14,
      time: 6_000,
      revenueBase: 540,
    },
    lotus: {
      name: 'Flor de loto',
      description: 'Elegancia en el agua.',
      img: 'item_lotus.png',
      costBase: 8_640,
      rateGrowth: 1.13,
      time: 12_000,
      revenueBase: 4_320,
    },
    frog: {
      name: 'Rana',
      description: '¡Croac-avillosa compañía!',
      img: 'item_frog.png',
      costBase: 103_680,
      rateGrowth: 1.12,
      time: 24_000,
      revenueBase: 51_840,
    },
    koi: {
      name: 'Peces koi',
      description: 'Estanque de colores.',
      img: 'item_koi.png',
      costBase: 1_244_160,
      rateGrowth: 1.11,
      time: 96_000,
      revenueBase: 622_080,
    },
    fountain: {
      name: 'Fuente Aleteo',
      description: 'Sacudiendo el plumaje.',
      img: 'item_fountain.png',
      costBase: 14_929_920,
      rateGrowth: 1.10,
      time: 384_000,
      revenueBase: 7_464_960,
    },
    lantern: {
      name: 'Farolillos',
      description: 'Ambientazo nocturno.',
      img: 'item_lantern.png',
      costBase: 179_159_040,
      rateGrowth: 1.09,
      time: 1_536_000,
      revenueBase: 89_579_520,
    },
    thermalBath: {
      name: 'Baño termal',
      description: '¡Relaja tus plumas!',
      img: 'item_thermal_bath.png',
      costBase: 2_149_908_480,
      rateGrowth: 1.08,
      time: 6_144_000,
      revenueBase: 1_074_954_240,
    },
    house: {
      name: 'Casita patuna',
      description: 'Hogar pa-to\' la vida.',
      img: 'item_house.png',
      costBase: 25_798_901760,
      rateGrowth: 1.07,
      time: 36_864_000,
      revenueBase: 29_668_737_024,
    },
  },
  managers: {
    food: {
      name: 'Antony Pepperony',
      description: 'Alimenta a todos los patos del estanque',
      img: 'manager_food.png',
      cost: 1_000,
    },
    lily: {
      name: 'Lily Pily',
      description: 'Cuida de los nenúfares como si fueran sus hijos',
      img: 'manager_lily.png',
      cost: 15_000,
    },
    divingKit: {
      name: 'Lucas Bucez',
      description: 'Encargado de repartir equipos de buceo',
      img: 'manager_diving_kit.png',
      cost: 100_000,
    },
    lotus: {
      name: 'Rosalinda',
      description: 'Cuida de las flores de loto con mucho cariño',
      img: 'manager_lotus.png',
      cost: 500_000,
    },
    frog: {
      name: 'Yoshito',
      description: 'Juega con la ranita y cuida de ella',
      img: 'manager_frog.png',
      cost: 1_200_000,
    },
    koi: {
      name: 'Sakura',
      description: 'Puedes dejarla a cargo de los peces koi... supongo',
      img: 'manager_koi.png',
      cost: 10_000_000,
    },
    fountain: {
      name: 'Splashi',
      description: 'Encargado de limpiar la Fuente Aleteo',
      img: 'manager_fountain.png',
      cost: 111_111_111,
    },
    lantern: {
      name: 'Hikari',
      description: 'Instala farolillos por todo el estanque',
      img: 'manager_lantern.png',
      cost: 555_555_000,
    },
    thermalBath: {
      name: 'Roberto Ducky',
      description: 'Encargado de mantener el agua caliente',
      img: 'manager_thermal_bath.png',
      cost: 1_0000_000_000,
    },
    house: {
      name: 'Inmobiliarias Jimmy',
      description: 'Trabaja duro para que los patos tengan un hogar',
      img: 'manager_house.png',
      cost: 100_000_000_000,
    },
  },
  upgrades: {
    food_1: {
      item: 'food',
      name: 'Comida gourmet',
      description: 'Aumenta la eficiencia de los panecillos',
      cost: 250_000,
      effect: 3,
    },
    lily_1: {
      item: 'lily',
      name: 'Nenúfares ergonómicos',
      description: 'Aumenta la eficiencia de los nenúfares',
      cost: 500_000,
      effect: 3,
    },
    divingKit_1: {
      item: 'divingKit',
      name: 'Buceo profundo',
      description: 'Aumenta la eficiencia de los equipos de buceo',
      cost: 1_000_000,
      effect: 3,
    },
    lotus_1: {
      item: 'lotus',
      name: 'Loto de la suerte',
      description: 'Aumenta la eficiencia de las flores de loto',
      cost: 5_000_000,
      effect: 3,
    },
    frog_1: {
      item: 'frog',
      name: 'Rana saltarina',
      description: 'Aumenta la eficiencia de la rana',
      cost: 10_000_000,
      effect: 3,
    },
    koi_1: {
      item: 'koi',
      name: 'Koi ornamentales',
      description: 'Aumenta la eficiencia de los peces koi',
      cost: 25_000_000,
      effect: 3,
    },
    fountain_1: {
      item: 'fountain',
      name: 'Fuente con música relajante',
      description: 'Aumenta la eficiencia de la Fuente Aleteo',
      cost: 500_000_000,
      effect: 3,
    },
    lantern_1: {
      item: 'lantern',
      name: 'Farolillos flotantes',
      description: 'Aumenta la eficiencia de los farolillos',
      cost: 10_000_000_000,
      effect: 3,
    },
    thermalBath_1: {
      item: 'thermalBath',
      name: 'Baño termal calentito',
      description: 'Aumenta la eficiencia del baño termal',
      cost: 50_000_000_000,
      effect: 3,
    },
    house_1: {
      item: 'house',
      name: 'Mansión Patuna',
      description: 'Aumenta la eficiencia de la Casita Patuna',
      cost: 250_000_000_000,
      effect: 3,
    },
    pond_1: {
      item: 'ALL',
      name: 'Estanque renovado',
      description: 'Aumenta la eficiencia de todo el estanque',
      cost: 1_000_000_000_000,
      effect: 3,
    },
  },
  achievements: {
    rare: {
      allAchievements: {
        name: '100%',
        description: 'Consigue todos los logros del juego',
        img: '/achievements/100.png',
      },
      kuroJam: {
        name: 'KuroPato',
        description: 'Juega durante la KuroJam 2023',
        img: '/skins/skin_kuro.png',
      },
    },
    easteregg: {
      konami: {
        name: 'El KonamiPato',
        description: '¿En serio te sabías el código? *ejem* Friki *cuack*',
        img: '/achievements/konami.png',
      },
    },
    cash: {
      '100': {
        name: 'Aspirante a patodólars',
        description: 'Consigue tus primeras 100 patomonedas',
        img: '/skins/skin_default_brown.png',
      },
      '50k': {
        name: 'Mentor de patitos',
        description: 'Acumula 50.000 patomonedas',
        img: '/brand/coin.png',
      },
      '100k': {
        name: 'Lord Patoso',
        description: 'Acumula 100.000 patomonedas',
        img: '/brand/coin.png',
      },
      '1M': {
        name: 'Millonario de plumitas',
        description: 'Acumula 1.000.000 patomonedas',
        img: '/brand/coin.png',
      },
      '500M': {
        name: 'Campeón del chapoteo',
        description: 'Acumula 500 millones de patomonedas',
        img: '/brand/coin.png',
      },
      '1KM': {
        name: 'Emperador de la pluma',
        description: 'Acumula 1.000 millones de patomonedas',
        img: '/brand/coin.png',
      },
      '1B': {
        name: 'Quacker mágico',
        description: 'Acumula 1 billón de patomonedas',
        img: '/brand/coin.png',
      },
      '10B': {
        name: 'Rey de la charca',
        description: 'Acumula 10 billones de patomonedas',
        img: '/brand/coin.png',
      },
      '1T': {
        name: 'Maestro del Cuack',
        description: 'Acumula 1 trillón de patomonedas',
        img: '/brand/coin.png',
      },
    },
    itemLevel: {
      food_25: {
        name: 'Festín patoso',
        description: 'Panecillos nivel 25!',
        img: '/items/item_food.png',
      },
      food_50: {
        name: 'Banquete acuático',
        description: 'Panecillos nivel 50!',
        img: '/items/item_food.png',
      },
      food_100: {
        name: 'Maestro Chef de Patos',
        description: 'Panecillos nivel 100!',
        img: '/items/item_food.png',
      },
      food_200: {
        name: 'Pato Gourmet',
        description: 'Panecillos nivel 200!',
        img: '/items/item_food.png',
      },
      lily_25: {
        name: 'Salto inicial',
        description: 'Nenúfar nivel 25!',
        img: '/items/item_lily.png',
      },
      lily_50: {
        name: 'Paseo Flotante',
        description: 'Nenúfar nivel 50!',
        img: '/items/item_lily.png',
      },
      lily_100: {
        name: 'Jardín de Patos',
        description: 'Nenúfar nivel 100!',
        img: '/items/item_lily.png',
      },
      lily_200: {
        name: 'Maestro de los estanques',
        description: 'Nenúfar nivel 200!',
        img: '/items/item_lily.png',
      },
      divingKit_25: {
        name: 'Buceo Inicial',
        description: 'Equipo de buceo nivel 25!',
        img: '/items/item_diving_kit.png',
      },
      divingKit_50: {
        name: 'Submarinista Patoso',
        description: 'Equipo de buceo nivel 50!',
        img: '/items/item_diving_kit.png',
      },
      divingKit_100: {
        name: 'Ducktonauta acuático',
        description: 'Equipo de buceo nivel 100!',
        img: '/items/item_diving_kit.png',
      },
      divingKit_200: {
        name: 'Explorador subacuático',
        description: 'Equipo de buceo nivel 200!',
        img: '/items/item_diving_kit.png',
      },
      lotus_25: {
        name: 'Loto Naciente',
        description: 'Flor de loto nivel 25!',
        img: '/items/item_lotus.png',
      },
      lotus_50: {
        name: 'Jardín floral',
        description: 'Flor de loto nivel 50!',
        img: '/items/item_lotus.png',
      },
      lotus_100: {
        name: 'Cultivador de paz',
        description: 'Flor de loto nivel 100!',
        img: '/items/item_lotus.png',
      },
      lotus_200: {
        name: 'Emperador del estanque',
        description: 'Flor de loto nivel 200!',
        img: '/items/item_lotus.png',
      },
      frog_25: {
        name: 'Pato saltarín',
        description: 'Ranita nivel 25!',
        img: '/skins/skin_frog.png',
      },
      frog_50: {
        name: 'Amigo anfibio',
        description: 'Ranita nivel 50!',
        img: '/items/item_frog.png',
      },
      frog_100: {
        name: 'Soberano de los sapos',
        description: 'Ranita nivel 100!',
        img: '/items/item_frog.png',
      },
      frog_200: {
        name: 'Reino de los saltos',
        description: 'Ranita nivel 200!',
        img: '/items/item_frog.png',
      },
      koi_25: {
        name: 'Estanque oriental',
        description: 'Peces koi nivel 25!',
        img: '/items/item_koi.png',
      },
      koi_50: {
        name: 'Acuario viviente',
        description: 'Peces koi nivel 50!',
        img: '/items/item_koi.png',
      },
      koi_100: {
        name: 'Zen acuático',
        description: 'Peces koi nivel 100!',
        img: '/items/item_koi.png',
      },
      koi_200: {
        name: 'Dragón dorado',
        description: 'Peces koi nivel 200!',
        img: '/items/item_koi.png',
      },
      fountain_25: {
        name: 'Gotas de diversión',
        description: 'Fuente Aleteo nivel 25!',
        img: '/items/item_fountain.png',
      },
      fountain_50: {
        name: 'Parque acuático',
        description: 'Fuente Aleteo nivel 50!',
        img: '/items/item_fountain.png',
      },
      fountain_100: {
        name: 'Cascada de patos',
        description: 'Fuente Aleteo nivel 100!',
        img: '/items/item_fountain.png',
      },
      fountain_200: {
        name: 'Maestro de las aguas',
        description: 'Fuente Aleteo nivel 200!',
        img: '/items/item_fountain.png',
      },
      lantern_25: {
        name: 'Iluminador nocturno',
        description: 'Farolillos nivel 25!',
        img: '/items/item_lantern.png',
      },
      lantern_50: {
        name: 'Sendero Luminoso',
        description: 'Farolillos nivel 50!',
        img: '/items/item_lantern.png',
      },
      lantern_100: {
        name: 'Festival de luces',
        description: 'Farolillos nivel 100!',
        img: '/items/item_lantern.png',
      },
      lantern_200: {
        name: 'Maestro de la luz',
        description: 'Farolillos nivel 200!',
        img: '/items/item_lantern.png',
      },
      thermalBath_25: {
        name: 'Relax acuático',
        description: 'Baño termal nivel 25!',
        img: '/items/item_thermal_bath.png',
      },
      thermalBath_50: {
        name: 'Spa de plumitas',
        description: 'Baño termal nivel 50!',
        img: '/items/item_thermal_bath.png',
      },
      thermalBath_100: {
        name: 'Ducktástico Descanso',
        description: 'Baño termal nivel 100!',
        img: '/items/item_thermal_bath.png',
      },
      thermalBath_200: {
        name: 'Maestro del baño',
        description: 'Baño termal nivel 200!',
        img: '/items/item_thermal_bath.png',
      },
      house_25: {
        name: 'Pato de alquiler',
        description: 'Casita patuna nivel 25!',
        img: '/items/item_house.png',
      },
      house_50: {
        name: 'Hogar acolchado',
        description: 'Casita patuna nivel 50!',
        img: '/items/item_house.png',
      },
      house_100: {
        name: 'Nido de Comodidad',
        description: 'Casita patuna nivel 100!',
        img: '/items/item_house.png',
      },
      house_200: {
        name: 'Palacio de plumas',
        description: 'Casita patuna nivel 200!',
        img: '/items/item_house.png',
      },
    },
  },
  skins: {
    default: {
      name: 'Pato',
      description: '¿En serio te vas a quedar con el pato por defecto?',
      img: '/skins/skin_default.png',
    },
    defaultBrown: {
      name: 'Pato marrón',
      description: 'Vale, este es un poco mejor',
      img: '/skins/skin_default_brown.png',
    },
    kuro: {
      name: 'KuroPato',
      description: '🤓☝',
      img: '/skins/skin_kuro.png',
    },
    frog: {
      name: 'RanaPato',
      description: 'Mejor amigo de la ranita del estanque',
      img: '/skins/skin_frog.png',
    },
  },
})
